module.exports = {
  beforeEach(browser, done) {
    browser.resizeWindow(1280, 800, done);
  },
  'Edit user profile and delete account': function (browser) {
    browser
      .url('http://localhost:8000')
      .assert.title('Jed-Doc Manager')
      .assert.urlEquals('http://localhost:8000/')
      .waitForElementVisible('nav', 1000)
      .waitForElementVisible('#login', 100000)
      .click('#login')
      .assert.urlEquals('http://localhost:8000/login')
      .setValue('input#query', 'jedidiah')
      .setValue('input#password', 'jedidiah')
      .click('div button[type="submit"]')
      .waitForElementVisible('div#test1', 10000)
      .assert.urlEquals('http://localhost:8000/dashboard')
      .waitForElementVisible('#mobile-nav', 10000)
      .click('#mobile-nav')
      .waitForElementVisible('#my-profile', 10000)
      .click('#my-profile')
      .waitForElementVisible('#editUserBtn', 10000)
      .click('#editUserBtn')
      .waitForElementVisible('input#full_name', 10000)
      .waitForElementVisible('input#username', 10000)
      .waitForElementVisible('input#password', 10000)
      .waitForElementVisible('input#email', 10000)
      .clearValue('input#username')
      .setValue('input#username', 'NightWatch User')
      .clearValue('input#password')
      .setValue('input#password', 'NightWatchPassword')
      .click('#editUserSubmitBtn')
      .waitForElementVisible('.dropdown-button', 1000000)
      .click('.dropdown-button')
      .waitForElementVisible('#logoutDropDownBtn', 1000000)
      .click('#logoutDropDownBtn')
      .assert.urlEquals('http://localhost:8000/')
      .waitForElementVisible('nav', 1000)
      .waitForElementVisible('#login', 100000)
      .click('#login')
      .assert.urlEquals('http://localhost:8000/login')
      .setValue('input#query', 'NightWatch User')
      .setValue('input#password', 'NightWatchPassword')
      .click('div button[type="submit"]')
      .waitForElementVisible('div#test1', 10000)
      .assert.urlEquals('http://localhost:8000/dashboard')
      .waitForElementVisible('#mobile-nav', 10000)
      .click('#mobile-nav')
      .waitForElementVisible('#my-profile', 10000)
      .click('#my-profile')
      .pause(2000)
      .assert.urlEquals('http://localhost:8000/my-profile')
      .waitForElementVisible('#deleteUserBtn', 10000)
      .click('#deleteUserBtn')
      .acceptAlert()
      .pause(10000)
      .assert.urlEquals('http://localhost:8000/')
      .end();
  },
};
