export default {
  DELETE_SINGLE_USER_SUCCESS_EXPECTED_STATE: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 4,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
      allUsers: {
        count: 6,
        page: 1,
        pageCount: 1,
        pageSize: 6,
        totalCount: 6,
        users: [{
          id: 1,
          fullname: 'Samara Stracke PhD',
          username: 'Max_Borer',
          email: 'Reyna.Torphy@hotmail.com',
          roleId: 3,
          password: '$2a$08$KPhQp3dHfCaDEoAZ6KmXiukUOwMDsvm9poOJNCI1tpk5sZoYEs4my',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 2,
          fullname: 'jonathan doe',
          username: 'john doe',
          email: 'Tania92@yahoo.com',
          roleId: 3,
          password: '$2a$08$76j1vujLbWLdS8K3zCgiGes/OP.lxzMyWDRL7dw6.fej5SBlvuVxi',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 3,
          fullname: 'dede',
          username: 'dede',
          email: 'Frederique44@yahoo.com',
          roleId: 1,
          password: '$2a$08$xiJEybtOvPA163fka4Ma6.A/5M4TvKskpqy2HMmydl6JS6vx/arAu',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 4,
          fullname: 'q',
          username: 'q',
          email: 'qq1be@email.com',
          roleId: 1,
          password: '$2a$08$EyNLxwbvwENfI.yf/zswLOpY2ysC6XKEqEqgYQABNhLMtU9MtHrDq',
          createdAt: '2017-06-05T11:55:11.608Z',
          updatedAt: '2017-06-05T11:55:11.608Z',
        }, {
          id: 20,
          fullname: 'Curt Walter',
          username: 'Kade_Rempel68',
          email: 'Gabriel.Goldner83@hotmail.com',
          roleId: 2,
          password: '$2a$08$vGRhr8ZKerc1jPTW2KHo0uoVFX.rJRP0ZhFFbQIXAa6c0YznWIdY.',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-06T12:44:06.350Z',
        }],
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  LOAD_ALL_DOCUMENTS_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 12,
        username: 'qq',
        fullname: 'qq',
        roleId: 1,
        email: 'qq1e@email.com',
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: {
        count: 10,
        page: 2,
        pageCount: 2,
        pageSize: 2,
        totalCount: 10,
        documents: [{
          id: 8,
          title: 'test document 7r',
          body: 'Voluptatibus et quos ut culpa mollitia amet voluptas ratione id. Error nesciunt eos libero ratione. Aliquam dolore qui similique nemo qui dolorem et. Omnis praesentium ducimus maiores cum.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-05-26T16:41:07.867Z',
          updatedAt: '2017-06-01T15:29:34.760Z',
          userId: 12,
          User: {
            fullname: 'qq',
          },
        }, {
          id: 7,
          title: 'test document 6e',
          body: 'Aspernatur eum at dolor quae. Quo dignissimos rerum voluptas ducimus sit. Nihil minus sed dolores delectus earum error cumque. Quod dolorem ullam repellendus facere architecto.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-05-26T16:41:07.867Z',
          updatedAt: '2017-06-01T15:30:34.285Z',
          userId: 12,
          User: {
            fullname: 'qq',
          },
        }],
      },
    },
    user: [],
    role: [],
  },
  LOAD_ALL_USERS_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 4,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
      allUsers: {
        count: 6,
        page: 1,
        pageCount: 1,
        pageSize: 6,
        totalCount: 6,
        users: [{
          id: 21,
          fullname: 'Alvah Shanahan',
          username: 'Jacynthe.Will',
          email: 'Geraldine79@gmail.com',
          roleId: 2,
          password: '$2a$08$TMey3z1W6b1pbtD3qvdjauU7686vQlcwFxs15KNwaXp8weB4t8xr2',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 1,
          fullname: 'Samara Stracke PhD',
          username: 'Max_Borer',
          email: 'Reyna.Torphy@hotmail.com',
          roleId: 3,
          password: '$2a$08$KPhQp3dHfCaDEoAZ6KmXiukUOwMDsvm9poOJNCI1tpk5sZoYEs4my',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 2,
          fullname: 'jonathan doe',
          username: 'john doe',
          email: 'Tania92@yahoo.com',
          roleId: 3,
          password: '$2a$08$76j1vujLbWLdS8K3zCgiGes/OP.lxzMyWDRL7dw6.fej5SBlvuVxi',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 3,
          fullname: 'dede',
          username: 'dede',
          email: 'Frederique44@yahoo.com',
          roleId: 1,
          password: '$2a$08$xiJEybtOvPA163fka4Ma6.A/5M4TvKskpqy2HMmydl6JS6vx/arAu',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 4,
          fullname: 'q',
          username: 'q',
          email: 'qq1be@email.com',
          roleId: 1,
          password: '$2a$08$EyNLxwbvwENfI.yf/zswLOpY2ysC6XKEqEqgYQABNhLMtU9MtHrDq',
          createdAt: '2017-06-05T11:55:11.608Z',
          updatedAt: '2017-06-05T11:55:11.608Z',
        }, {
          id: 20,
          fullname: 'Curt Walter',
          username: 'Kade_Rempel68',
          email: 'Gabriel.Goldner83@hotmail.com',
          roleId: 2,
          password: '$2a$08$vGRhr8ZKerc1jPTW2KHo0uoVFX.rJRP0ZhFFbQIXAa6c0YznWIdY.',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-06T12:44:06.350Z',
        }],
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  UPDATE_SINGLE_USER_BY_ADMIN_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 4,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
      allUsers: {
        count: 6,
        page: 1,
        pageCount: 1,
        pageSize: 6,
        totalCount: 6,
        users: [{
          id: 21,
          fullname: 'Alvah Shanahan',
          username: 'Jacynthe.Will',
          email: 'Geraldine79@gmail.com',
          roleId: 2,
          password: '$2a$08$TMey3z1W6b1pbtD3qvdjauU7686vQlcwFxs15KNwaXp8weB4t8xr2',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 1,
          fullname: 'Samara Stracke PhD',
          username: 'Max_Borer',
          email: 'Reyna.Torphy@hotmail.com',
          roleId: 3,
          password: '$2a$08$KPhQp3dHfCaDEoAZ6KmXiukUOwMDsvm9poOJNCI1tpk5sZoYEs4my',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 2,
          fullname: 'jonathan doe',
          username: 'john doe',
          email: 'Tania92@yahoo.com',
          roleId: 3,
          password: '$2a$08$76j1vujLbWLdS8K3zCgiGes/OP.lxzMyWDRL7dw6.fej5SBlvuVxi',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 3,
          fullname: 'dede',
          username: 'dede',
          email: 'Frederique44@yahoo.com',
          roleId: 1,
          password: '$2a$08$xiJEybtOvPA163fka4Ma6.A/5M4TvKskpqy2HMmydl6JS6vx/arAu',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
        }, {
          id: 4,
          fullname: 'q',
          username: 'q',
          email: 'qq1be@email.com',
          roleId: 1,
          password: '$2a$08$EyNLxwbvwENfI.yf/zswLOpY2ysC6XKEqEqgYQABNhLMtU9MtHrDq',
          createdAt: '2017-06-05T11:55:11.608Z',
          updatedAt: '2017-06-05T11:55:11.608Z',
        }, {
          fullname: 'Curt Walter',
          username: 'Kade_Rempel68',
          email: 'Gabriel.Goldner83@hotmail.com',
          roleId: '2',
        }],
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  LOAD_USER_DOCUMENT_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 4,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: {
        count: 2,
        documents: [{
          id: 29,
          title: 'qqq',
          body: 'qqq',
          access: 'public',
          ownerRoleId: 1,
          createdAt: '2017-06-06T13:24:28.872Z',
          updatedAt: '2017-06-06T13:24:28.872Z',
          userId: 4,
          User: {
            fullname: 'q',
          },
        }, {
          id: 27,
          title: ' dd',
          body: ' ddfffffffff',
          access: 'private',
          ownerRoleId: 3,
          createdAt: '2017-06-05T11:56:26.838Z',
          updatedAt: '2017-06-05T12:03:34.687Z',
          userId: 4,
          User: {
            fullname: 'q',
          },
        }],
      },
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  UPDATE_USER_DOCUMENT_SUCCESS: {
    flashMessages: [{
      id: 1,
      text: 'Document successfuly updated',
    }],
    login: {
      isAuthenticated: true,
      user: {
        id: 6,
        username: 'jed',
        fullname: 'jed',
        roleId: 3,
        email: 'jed@email.com',
      },
    },
    documents: {
      MyDocuments: {
        documents: [{
          id: 40,
          title: 'dd1',
          body: 'ddd',
          access: 'public',
          ownerRoleId: 3,
          createdAt: '2017-06-06T14:29:24.091Z',
          updatedAt: '2017-06-06T14:29:38.651Z',
          userId: 6,
        }],
      },
    },
    user: [],
    role: [],
  },
  DELETE_USER_DOCUMENT_SUCCESS: {
    flashMessages: [{
      id: 1,
      text: 'Document deleted successfully.',
    }],
    login: {
      isAuthenticated: true,
      user: {
        id: 6,
        username: 'jed',
        fullname: 'jed',
        roleId: 3,
        email: 'jed@email.com',
      },
    },
    documents: {
      MyDocuments: {
        documents: [],
      },
    },
    user: [],
    role: [],
  },
  LOAD_WELCOME_PAGE_DOCUMENT_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: false,
    },
    documents: {
      PublicDocuments: [{
        id: 2,
        title: 'Fake title document',
        body: 'Quidem qui cum voluptas natus est adipisci placeat aliquid aut. Qui reiciendis voluptatibus officia dolores consequatur est. Accusamus et repellat dolores officiis aut fuga voluptas.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 3,
        title: 'test document 2',
        body: 'Mollitia ea accusantium debitis adipisci odio nam neque. Earum nam atque non ab doloribus. Iusto ratione aut officiis et omnis rerum aut odit.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 4,
        title: 'test document 3',
        body: 'Ut ipsa alias est vero voluptatem voluptatem adipisci eos. Quia velit alias ea dolore. Sed rerum aut dolore veniam ipsa hic quo laboriosam. Aut hic sed. Est esse et minima alias voluptatem in porro pariatur accusamus. Mollitia illum molestias libero rerum quisquam.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 5,
        title: 'test document 4',
        body: 'Ducimus quasi unde. Rerum laudantium ducimus alias. Optio recusandae consequatur laboriosam nesciunt ut. Nihil mollitia eum et rerum et qui quia sint. Delectus delectus officiis exercitationem dolor corporis doloremque deserunt ea eos.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 6,
        title: 'test document 5',
        body: 'Repellendus amet sapiente nam neque. In fuga est velit possimus dicta. Nihil pariatur sunt repellat minus. Blanditiis suscipit qui enim illum placeat voluptatem.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 7,
        title: 'test document 6',
        body: 'Nihil numquam omnis. Ut excepturi assumenda dolorem maxime. Illum ut ullam voluptatum consequatur eligendi non eos dolore. Omnis sequi distinctio molestias. Nihil molestias pariatur. Ut voluptatibus est fugit molestiae.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 8,
        title: 'test document 7',
        body: 'Reprehenderit nulla ut iusto vitae assumenda et aut nesciunt hic. Adipisci est nostrum autem aliquid dignissimos. Minus suscipit similique. Quidem est quod expedita.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 9,
        title: 'test document 8',
        body: 'Exercitationem eum sed quos animi. Nam vel tempora id ullam repellendus illum qui perspiciatis nemo. Alias et laudantium natus aliquam. Dolores voluptatum ut. Quia non ut mollitia voluptas et.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 10,
        title: 'test document 9',
        body: 'Voluptatem voluptatem quod exercitationem quo ut earum nisi. Magnam quas dolores sit vel animi vitae. Molestiae sint accusamus quibusdam odio necessitatibus. Quos quis qui.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 11,
        title: 'test document 10',
        body: 'Veniam doloribus vel. Non vel quidem velit et soluta. Sequi et rerum ut numquam labore maiores excepturi corporis provident. Voluptas molestias veniam nam natus eligendi voluptate provident sequi. Inventore qui suscipit ut eos placeat autem repudiandae exercitationem aut.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 12,
        title: 'test document 11',
        body: 'Omnis explicabo voluptas exercitationem qui voluptate ipsam voluptatum. Minus esse impedit dolor ut itaque nihil accusamus praesentium officia. Vel quia voluptates aut iure facilis consequatur veniam et veritatis. Reprehenderit quia veritatis quis eos itaque. Et itaque quo voluptas qui dolorum voluptatem ipsa. Quidem voluptas saepe nesciunt optio.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 13,
        title: 'test document 12',
        body: 'Impedit quisquam non. Tempora distinctio corporis. Et aperiam praesentium dolor alias eum.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 14,
        title: 'test document 13',
        body: 'Ratione enim fugiat iure veniam dolorem sed vero unde. Dolorem quia iusto quidem. Ut voluptates non molestiae quos facere rerum animi et quos. Quisquam et quia velit sit quis magni. Autem similique natus et blanditiis vel dolorem. Perspiciatis repudiandae incidunt temporibus maxime aut ut enim.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 15,
        title: 'test document 14',
        body: 'Non perspiciatis doloribus voluptate odio consequuntur sed sed aperiam explicabo. Et porro est odio omnis. Reiciendis repellendus ut corrupti accusantium. Et omnis nam inventore nostrum alias non aliquid quis. Sequi vel est modi omnis laborum.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 16,
        title: 'test document 15',
        body: 'Modi sed dicta. Voluptas facere veritatis corporis qui est voluptatibus voluptatem reprehenderit. Enim corrupti qui quibusdam cupiditate illum odit quibusdam. Nihil non ad omnis ut laborum sunt est.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 17,
        title: 'test document 16',
        body: 'Cum sequi ad iusto voluptatem ex omnis incidunt iusto. Quia beatae porro sit. Vel eos voluptatem repudiandae. Exercitationem debitis veritatis id.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 18,
        title: 'test document 17',
        body: 'Aut quo enim deleniti ipsam. Harum dolorum et culpa minus numquam est quas. Enim labore qui quo et. Aspernatur qui sequi rem vero recusandae ullam omnis. Sunt cupiditate velit aperiam quia tempore sit aperiam praesentium.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }, {
        id: 19,
        title: 'test document 18',
        body: 'Exercitationem et fuga rerum laborum qui ipsa fuga. Et voluptas tempore quod laudantium repellat nesciunt ut. Ex ut in sit et nihil architecto ad. Recusandae ut rerum autem rerum odit dolore doloribus.',
        access: 'public',
        ownerRoleId: 2,
        createdAt: '2017-05-19T18:54:41.705Z',
        updatedAt: '2017-05-19T18:54:41.705Z',
        userId: 1,
        User: {
          fullname: 'Marlon Paucek',
        },
      }],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  LOAD_AUTHORIZED_TO_VIEW_DOCUMENT_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 4,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: {
        documents: [{
          id: 29,
          title: 'qqq',
          body: 'qqq',
          access: 'public',
          ownerRoleId: 1,
          createdAt: '2017-06-06T13:24:28.872Z',
          updatedAt: '2017-06-06T13:24:28.872Z',
          userId: 4,
          User: {
            fullname: 'q',
          },
        }],
      },
      AuthToViewDocuments: [],
      allDocuments: [],
      AuthorizeToViewDocuments: {
        count: 15,
        page: 1,
        pageCount: 2,
        pageSize: 8,
        totalCount: 15,
        documents: [{
          id: 1,
          title: 'modi quo eaque',
          body: 'Officia maxime nemo assumenda rem provident similique.',
          access: 'private',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 7,
          title: 'test document 6',
          body: 'Rem numquam laborum vitae est necessitatibus ut velit cupiditate. Alias rerum laborum et dolorum. Omnis illo explicabo. Distinctio omnis consectetur impedit aliquid. Quibusdam qui et fugit explicabo possimus similique.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 8,
          title: 'test document 7',
          body: 'Ut neque rerum et eos eos dolores nihil. Corporis in vero quos maiores eos. Qui id quibusdam soluta labore quo molestiae cupiditate quis reiciendis. Et deserunt aut repudiandae aut quod consequatur neque aut.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 11,
          title: 'test document 10',
          body: 'Officiis corporis tempore. Perspiciatis labore itaque sit veritatis ut ratione esse dolor. Rerum voluptates similique debitis blanditiis qui recusandae. Ut libero iste. Enim quia aut.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 12,
          title: 'test document 11',
          body: 'Quis et eaque autem aut. Eum similique natus sunt blanditiis. Nostrum quia consequuntur. Distinctio alias ipsum. Omnis et non voluptatum dicta quia ea.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 13,
          title: 'test document 12',
          body: 'Eum corrupti odit dolorem cupiditate. Officiis possimus eos. Quos et sint incidunt.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 15,
          title: 'test document 14',
          body: 'Consequatur non odit quo. Ut mollitia incidunt porro quibusdam quidem accusantium. Rerum qui explicabo maiores ullam iste. Possimus ut dolorum praesentium et magni quidem et laboriosam fugit. Debitis quos perferendis aliquam sapiente nam velit.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }, {
          id: 16,
          title: 'test document 15',
          body: 'Qui est ut aut ea voluptate enim. Nulla fuga excepturi minus nihil. Corrupti at exercitationem ducimus in enim sed veritatis. Ducimus et voluptatem odit officia. Doloribus soluta aut assumenda perferendis ducimus. A officia praesentium pariatur qui.',
          access: 'public',
          ownerRoleId: 2,
          createdAt: '2017-06-05T11:53:33.457Z',
          updatedAt: '2017-06-05T11:53:33.457Z',
          userId: 1,
          User: {
            fullname: 'Samara Stracke PhD',
          },
        }],
      },
    },
    user: [],
    role: [],
  },
  CREATE_DOCUMENT_BY_USER_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 6,
        username: 'q',
        fullname: 'q',
        roleId: 3,
        email: 'qq1bqe@email.com',
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  SEARCH_USER_BY_USERNAME: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 4,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
      allUsers: {
        count: 1,
        page: 1,
        pageCount: 1,
        pageSize: 6,
        totalCount: 6,
        users: [{
          id: 3,
          fullname: 'dede',
          username: 'dede',
          email: 'Frederique44@yahoo.com',
          roleId: 1,
          password: '$2a$08$xiJEybtOvPA163fka4Ma6.A/5M4TvKskpqy2HMmydl6JS6vx/arAu',
          createdAt: '2017-06-05T11:53:33.313Z',
          updatedAt: '2017-06-05T11:53:33.321Z',
          documents: [],
        }],
        metaData: {
          page: 1,
          pageCount: 1,
          pageSize: 1,
          totalCount: 1,
        },
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  SEARCH_DOCUMENTS_BY_TITLE_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 3,
        username: 'q',
        fullname: 'q',
        roleId: 1,
        email: 'qq1be@email.com',
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  SET_CURRENT_USER: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 7,
        username: 'jerry',
        fullname: 'jerry',
        roleId: 3,
        email: 'jerry@ff.com',
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  LOAD_USER_PROFILE_SUCCESS: {
    flashMessages: [],
    login: {
      isAuthenticated: true,
      user: {
        id: 7,
        fullname: 'jerry',
        username: 'jerry',
        email: 'jerry@ff.com',
        roleId: 3,
        password: '$2a$08$b.rXG69qFkdd3jGnLVrfUewpAC0zYx4vZifhMTKkwEJxG4n7lVAGO',
        createdAt: '2017-05-20T14:01:40.065Z',
        updatedAt: '2017-05-20T14:01:40.065Z',
        documents: [],
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },
  UPDATE_USER_PROFILE_SUCCESS: {
    flashMessages: [{
      id: 1,
      text: 'User updated successfully.',
    }],
    login: {
      isAuthenticated: true,
      user: {
        id: 7,
        fullname: 'jerry',
        username: 'jerry',
        email: 'jerry@ff.com',
        roleId: 3,
        password: '$2a$08$mXt6ErO1NQVw4j/lkBsIseLxX7haeonkmgh9svP5XJQXC5oo02Z1a',
        createdAt: '2017-05-20T14:01:40.065Z',
        updatedAt: '2017-05-20T14:01:40.065Z',
        documents: [],
      },
    },
    documents: {
      PublicDocuments: [],
      MyDocuments: [],
      AuthToViewDocuments: [],
      allDocuments: [],
    },
    user: [],
    role: [],
  },

};
